define("params", [], () => {

  let params = {
    size: 16,
    zoom: 2,
    images: [{
        img: "images/font.png",
        name: "pixelFont"
      }, {
        img: "images/cursor.png",
        name: "cursor"
      }, {
        img: "images/title.png",
        name: "title"
      }, {
        img: "images/player.png",
        name: "playerSprite",
        frames: 12,
        lines: 1
      }, {
        img: "images/explosion.png",
        name: "explosion",
        frames: 9,
        lines: 1
      }, {
        img: "images/tiles.png",
        name: "tiles"
      }, {
        img: "images/exit.png",
        name: "exit",
        frames: 10
      }, {
        img: "images/dust.png",
        name: "dust",
        frames: 9,
        lines: 1
      }, {
        img: "images/pattern.png",
        name: "pattern"
      }, {
        img: "images/lock.png",
        name: "lock"
      }],
    sounds: [{
        url: "sounds/mouvement.wav",
        name: "mouvement"
      }, {
        url: "sounds/selection.wav",
        name: "selection"
      }, {
        url: "sounds/bravo.wav",
        name: "bravo"
      }, {
        url: "sounds/validation.wav",
        name: "validation"
      }, {
        url: "sounds/appearance.wav",
        name: "appearance"
      }, {
        url: "sounds/block.wav",
        name: "block"
      }],
    tiles: [{
        type: "tile",
        name: "water",
        id: 0,
        collision: true,
        apparence: "auto",
        lines: 3
      }, {
        type: "tile",
        name: "grass",
        id: 1,
        collision: false,
        apparence: 1
      }, {
        type: "tile",
        name: "wall",
        id: 2,
        collision: true,
        apparence: "auto",
        lines: 1
      }, {
        type: "tile",
        name: "ice",
        action: "ice",
        id: 3,
        collision: false,
        apparence: "auto",
        lines: 2
      }, {
        type: "sprite",
        name: "next",
        id: 4,
        collision: false,
        action: "next",
        apparence: "exit",
        lines: 2,
        speed: 0.3
      }, {
        type: "tile",
        name: "player",
        id: 5,
        collision: false,
        apparence: 5
      }, {
        type: "tile",
        name: "trap",
        action: "trap",
        id: 6,
        collision: false,
        apparence: 6
      }, {
        type: "tile",
        name: "hole",
        id: 7,
        collision: true,
        apparence: 7
      }, {
        type: "tile",
        name: "barrier",
        id: 8,
        collision: true,
        apparence: "auto",
        lines: 4
      }, {
        type: "tile",
        name: "arrowLeft",
        action: "left",
        id: 9,
        collision: false,
        apparence: 9
      }, {
        type: "tile",
        name: "arrowTop",
        action: "top",
        id: 10,
        collision: false,
        apparence: 10
      }, {
        type: "tile",
        name: "arrowRight",
        action: "right",
        id: 11,
        collision: false,
        apparence: 11
      }, {
        type: "tile",
        name: "arrowDown",
        action: "bottom",
        id: 12,
        collision: false,
        apparence: 12
      }]
  }

  return params

})