let data = [
  "Lorem",
  "ipsum",
  "dolor",
  "sit",
  "amet,",
  "consectetur",
  "adipisicing",
  "elit.",
  "Ipsam",
  "consectetur",
  "beatae",
  "quidem,",
  "officiis",
  "nobis!",
  "Maiores",
  "eaque",
  "distinctio",
  "reiciendis",
  "cupiditate,",
  "voluptatibus",
  "sit",
  "non",
  "repellat",
  "amet,",
  "harum",
  "sunt",
  "quasi",
  "hic",
  "eos!",
  "Dignissimos.",
];

let search = new Wade(data);

console.log(search("ip").sort((a, b) => a.score - b.score).map(item => data[item.index]))