<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>Dashboard</title>
  <link rel="stylesheet" href="<?php print css('spectre') ?>">
  <link rel="stylesheet" href="<?php print css('main') ?>">
  <script src="<?php print js('zepto.min') ?>"></script>
  <script src="<?php print js('main') ?>"></script>
</head>
<body>

  <div class="main-header">
    <div class="container">
      <div class="navbar">
        <div class="navbar-section">
          <a href="<?php print base_url() ?>" class="navbar-brand">
            Content System
          </a>
        </div>
        <div class="navbar-section">
          <a href="<?php print base_url('collections') ?>"
            class="btn btn-link">Collections</a>
          <a href="<?php print base_url('content') ?>"
            class="btn btn-link">Content</a>
          <a href="<?php print base_url('settings') ?>"
            class="btn btn-link">Settings</a>
          <a href="<?php print base_url('logout') ?>" class="btn btn-link">
            Logout (<?php print session('user')['nickname'] ?>)
          </a>
        </div>
      </div>
    </div>
  </div>

  <div class="container">
    <?php print $body ?>
  </div>

  <?php if ($error) { ?>
    <div id="alerts">

      <div class="toast toast-error">
        <button class="btn btn-clear float-right"></button>
        <?php print $error ?>
      </div>
    </div>
  <?php } ?>

  <script>
    $(".toast .btn-clear").on("click", function() {
      $(this).parent().remove()
    })
  </script>
</body>
</html>