<h2><?php print $collection ? 'Edit' : 'Create' ?> Collection</h2>
<form method="post">
  <div class="text-right">
    <button class="btn col-2">Save</button>
  </div>
  <div class="form-group">
    <label>Name</label>
    <input class="form-input" type="text" name="name" required>
  </div>
  <div class="form-group">
    <label>API identifier</label>
    <input class="form-input" type="text" name="id" required>
  </div>
  <div class="form-group">
    <label>Description</label>
    <textarea class="form-input" name="description"></textarea>
  </div>
</form>

<script>

</script>
