<h2>Collections</h2>

<div class="columns">
  <div class="column col-9">
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>Name</th>
          <th>Identifier</th>
          <th class="text-right">Updated</th>
        </tr>
      </thead>
      <tbody>
        <?php foreach ($collections as $collection) { ?>
          <tr onclick="location.href='<?php print base_url('collection/'.$collection['uid'].'/fields') ?>'">
            <td><?php print $collection['name'] ?></td>
            <td><?php print $collection['id'] ?></td>
            <td class="text-right"><?php print date("M d, Y", strtotime($collection['updated'])) ?></td>
          </tr>
        <?php } ?>
      </tbody>
    </table>
  </div>
  <div class="column col-3">
    <div class="text-center pt-10">
      <a href="#add-collection" class="btn">New collection</a>
    </div>
  </div>
</div>

<div class="modal" id="add-collection">
  <div class="modal-overlay"></div>
  <form class="modal-container" style="width:420px" method="post">
    <div class="modal-header">
      <a href="#" class="btn btn-clear float-right"></a>
      <div class="modal-title">New collection</div>
    </div>
    <div class="modal-body">
      <div class="content">
        <div class="form-group">
          <label>Name</label>
          <input class="form-input" type="text" name="name" required>
        </div>
        <div class="form-group">
          <label>Identifier</label>
          <input class="form-input" type="text" name="id" required>
        </div>
        <div class="form-group">
          <label>Description</label>
          <textarea class="form-input" name="description"></textarea>
        </div>
      </div>
    </div>
    <div class="modal-footer">
      <a href="#" class="btn btn-link btn-close">Close</a>
      <button class="btn btn-primary">Submit</button>
    </div>
  </form>
</div>

<script>
let input = Q('[name=name]')[0],
  output = Q('[name=id]')[0],
  listener = e => output.value = slugify(translit(e.target.value)),
  listener2 = e => {
    input.removeEventListener('input', listener)
    output.removeEventListener('input', listener2)
  }
if (!output.value) {
  input.addEventListener('input', listener)
  output.addEventListener('input', listener2)
}
location.hash = "#"
</script>