<!-- <h3>Fields</h3>
  <div class="text-right">
    <span class="btn col-2" onclick="addField()">Add field</span>
  </div>

  <template id="field-template">
    <div class="field">
      <div class="form-group">
        <label>Field name</label>
        <input class="form-input" type="text" name="fields[name][]" required>
      </div>
      <div class="form-group">
        <label>Field identifier</label>
        <input class="form-input" type="text" name="fields[id][]" required>
      </div>
      <div class="form-group">
        <label>Field type</label>
        <select class="form-select" name="[type]fields[]" onchange="changeFieldType(event)">
          <option value="string">String</option>
          <option value="text">Text</option>
          <option value="number">Number</option>
          <option value="media">Media</option>
          <option value="boolean">Boolean</option>
          <option value="reference">Reference</option>
        </select>
      </div>
      <div class="input-wrap">
        <div class="form-group">
          <label>Field value</label>
          <input class="form-input" type="text" name="[value]fields[]" required>
        </div>
      </div>
    </div>
  </template> -->


<script>
  function addField() {
    var html = Q("#field-template")[0].innerHTML;
    makeNode(html)
    Q("form")[0].appendChild(makeNode(html))
  }
  function changeFieldType(event) {
  }
</script>