<h2>"<?php print $collection['name']?>"</h2>

<div class="columns">
  <div class="column col-9">
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>Name</th>
          <th>Identifier</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <?php foreach ($collection['fields'] as $field) { ?>
          <tr>
            <td><?php print $field['name'] ?></td>
            <td><?php print $field['id'] ?></td>
            <td>
              <a class="btn btn-link"
                href="<?php print base_url('collection/'.$collection['uid'].'/fields/'.$field['id']) ?>">
                edit
              </a>
            </td>
          </tr>
        <?php } ?>
      </tbody>
    </table>
  </div>
  <div class="column col-3">
    <div class="text-center">
      <a href="#edit-collection" class="btn col-6 mb-10">Edit collection</a>
      <a href="#add-field" class="btn btn-primary col-6">New field</a>
    </div>
  </div>
</div>

<div class="modal" id="edit-collection">
  <div class="modal-overlay"></div>
  <form class="modal-container" style="width:420px" method="post">
    <div class="modal-header">
      <a href="#" class="btn btn-clear float-right"></a>
      <div class="modal-title">Edit collection</div>
    </div>
    <div class="modal-body">
      <div class="content">
        <input type="hidden" name="uid" value="<?php print $collection['uid'] ?>">
        <div class="form-group">
          <label>Field name</label>
          <input class="form-input" type="text" name="name"
            value="<?php print $collection['name'] ?>" required>
        </div>
        <div class="form-group">
          <label>Field type</label>
          <textarea class="form-input" name="description"><?php print $collection['description'] ?></textarea>
        </div>
      </div>
    </div>
    <div class="modal-footer">
      <a href="#" class="btn btn-link btn-close">Close</a>
      <button class="btn btn-primary">Submit</button>
    </div>
  </form>
</div>

<div class="modal" id="add-field">
  <div class="modal-overlay"></div>
  <form class="modal-container" style="width:420px" method="post">
    <div class="modal-header">
      <a href="#" class="btn btn-clear float-right"></a>
      <div class="modal-title">Add field</div>
    </div>
    <div class="modal-body">
      <div class="content">
        <div class="form-group">
          <label>Field name</label>
          <input class="form-input" type="text" name="field_name" required>
        </div>
        <div class="form-group">
          <label>Field identifier</label>
          <input class="form-input" type="text" name="field_id" required>
        </div>
        <div class="form-group">
          <label>Field type</label>
          <select class="form-select" name="field_type">
            <option value="string">String</option>
            <option value="text">Text</option>
            <option value="number">Number</option>
            <option value="media">Media</option>
            <option value="boolean">Boolean</option>
            <option value="reference">Reference</option>
          </select>
        </div>
      </div>
    </div>
    <div class="modal-footer">
      <a href="#" class="btn btn-link btn-close">Close</a>
      <button class="btn btn-primary">Submit</button>
    </div>
  </form>
</div>

<script>
let input = Q('[name=field_name]')[0],
  output = Q('[name=field_id]')[0],
  listener = e => output.value = slugify(translit(e.target.value)),
  listener2 = e => {
    input.removeEventListener('input', listener)
    output.removeEventListener('input', listener2)
  }
if (!output.value) {
  input.addEventListener('input', listener)
  output.addEventListener('input', listener2)
}
location.hash = "#"
</script>