<h2>"<?php print $collection['name']?>"</h2>

<div class="columns">
  <div class="column col-9">
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>Name</th>
          <th>Identifier</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <?php foreach ($collection['fields'] as $field) { ?>
          <tr>
            <td><?php print $field['name'] ?></td>
            <td><?php print $field['id'] ?></td>
            <td class="text-right">
              <a class="btn btn-link"
                href="<?php print base_url('collection/'.$collection['uid'].'/fields/'.$field['id']) ?>">
                action
              </a>
            </td>
          </tr>
        <?php } ?>
      </tbody>
    </table>
  </div>
  <div class="column col-3">
    <div class="text-center">
      <a href="#add-field" class="btn btn-primary col-6">New field</a>
      <a href="#edit-collection" class="btn btn-link btn-block">Edit</a>
      <a href="#delete-collection" class="btn btn-link btn-block">Delete</a>
    </div>
  </div>
</div>

<div class="modal" id="edit-collection">
  <div class="modal-overlay"></div>
  <form class="modal-container" style="width:420px" method="post">
    <div class="modal-header">
      <a href="#" class="btn btn-clear float-right"></a>
      <div class="modal-title">Edit collection</div>
    </div>
    <div class="modal-body">
      <div class="content">
        <div class="form-group">
          <label>Field name</label>
          <input class="form-input" type="text" name="name"
            value="<?php print $collection['name'] ?>" required>
        </div>
        <div class="form-group">
          <label>Field type</label>
          <textarea class="form-input" name="description" rows="6"
            maxlength="500"><?php print $collection['description'] ?></textarea>
        </div>
      </div>
    </div>
    <div class="modal-footer">
      <a href="#" class="btn btn-link btn-close">Close</a>
      <button class="btn btn-primary">Submit</button>
    </div>
  </form>
</div>

<div class="modal" id="delete-collection">
  <div class="modal-overlay"></div>
  <form class="modal-container" style="width:420px" method="post">
    <div class="modal-header">
      <a href="#" class="btn btn-clear float-right"></a>
      <div class="modal-title">Delete collection</div>
    </div>
    <div class="modal-body">
      <div class="content text-center">
        <p>Are you <strong>ABSOLUTELY</strong> sure?</p>
        <p>This action <strong>CANNOT</strong> be undone.
          This will permanently delete the
          "<strong><?php print $collection['name'] ?></strong>" collection.</p>
        <p>Please type in the name of the repository to confirm.</p>
        <div class="form-group">
          <input class="form-input" type="text" name="to_delete" required>
        </div>
      </div>
    </div>
    <div class="modal-footer">
      <button class="btn btn-block" disabled>
        I understand the consequences, delete this collection
      </button>
    </div>
  </form>
</div>

<div class="modal" id="add-field">
  <div class="modal-overlay"></div>
  <form class="modal-container" style="width:420px" method="post">
    <div class="modal-header">
      <a href="#" class="btn btn-clear float-right"></a>
      <div class="modal-title">Add field</div>
    </div>
    <div class="modal-body">
      <div class="content">
        <div class="form-group">
          <label>Field name</label>
          <input class="form-input" type="text" name="field_name"
            value="<?php print $field_name ?>" required>
        </div>
        <div class="form-group">
          <label>Field identifier</label>
          <input class="form-input" type="text" name="field_id"
            value="<?php print $field_id ?>" required>
        </div>
        <div class="form-group">
          <label>Field type</label>
          <select class="form-select" value="<?php print $field_type ?>"
            name="field_type">
            <option value="string">String</option>
            <option value="text">Text</option>
            <option value="number">Number</option>
            <option value="media">Media</option>
            <option value="boolean">Boolean</option>
            <option value="reference">Reference</option>
          </select>
        </div>
      </div>
    </div>
    <div class="modal-footer">
      <a href="#" class="btn btn-link btn-close">Close</a>
      <button class="btn btn-primary">Submit</button>
    </div>
  </form>
</div>

<script>
var input = $('[name=field_name]'),
  output = $('[name=field_id]')
if (!output.val()) {
  input.on('input', function() {
    output.val(slugify(translit(this.value)))
  })
  output.on('input', function() {
    input.off('input')
    output.off('input')
  })
}
var del_btn = $("#delete-collection button")[0]
$("[name=to_delete]").on('input', function() {
  if (this.value === "<?php print $collection['name'] ?>") {
    del_btn.removeAttribute("disabled")
  } else {
    del_btn.setAttribute("disabled", true)
  }
})
if ("<?php print $field_id ?>") {
  location.hash = "#add-field"
} else {
  location.hash = "#"
}
</script>