<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <link rel="stylesheet" href="<?php print config('url') . 'assets/css/spectre.css' ?>">
  <title>SignIn</title>
  <style>
    .auth-form {
      width: 260px;
      margin: 100px auto 0;
    }
    .auth-form h3 {
      text-align: center;
    }
    #alerts {
      position: absolute;
      top: 1rem;
      right: 1rem;
      width: 560px;
    }
  </style>
</head>
<body>
  <?php if ($error) { ?>
    <div id="alerts">
      <div class="toast toast-error"><?php print $error ?></div>
    </div>
  <?php } ?>
  <div class="auth-form">
    <h3 class="text-center">Sign in to System</h3>
    <form class="card" method="post">
      <div class="card-body">
        <div class="form-group">
          <label class="form-label" for="email">Email address</label>
          <input class="form-input" type="email" name="email" id="email"
            value="<?php print $email ?>">
        </div>
        <div class="form-group">
          <label class="form-label" for="password">Password</label>
          <input class="form-input" type="password" name="password" id="password">
        </div>
      </div>
      <div class="card-footer">
        <button class="btn btn-block">Sign in</button>
      </div>
    </form>
  </div>

</body>
</html>